import express from "express";
import upload from "..//middleware/multer.js";
import {protectroute} from "../middleware/auth.middleware.js";
import {signup,login,logout,updateprofile,checkauth} from "../controllers/auth.controller.js";
const router=express.Router();
router.post("/signup",signup);
router.post("/login",login);
router.post("/logout",logout);
router.put("/update-profile",protectroute,upload.single("profilepic"),updateprofile);
router.get("/check",protectroute,checkauth);
export default router;